### ISSUE TITLE
PCE server Exceptin when port in use

### ISSUE THREAD

**Issue by mohitc** [dtamal/Path-Computation-Element-Emulator#2]
PCE Server throws an Exception when the Server Port is in use by another application

**Comment by jonesir** [comment]
On fedora there's no exception been thrown, it runs perfect, just test it on windows, yes, a port has been in use.

Von Jason

Am 2012-7-15 um 14:27 schrieb mohitc reply@reply.github.com:

**Comment by mohitc** [comment]
I think if you launch a PCE Server instance and Launch another instance you get this exception (atleast on windows)

java.net.BindException: Address already in use: bind
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
    at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
    at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
    at com.pcee.architecture.networkmodule.NetworkModuleImpl.initSelectorParams(NetworkModuleImpl.java:339)
    at com.pcee.architecture.networkmodule.NetworkModuleImpl.start(NetworkModuleImpl.java:129)
    at com.pcee.architecture.networkmodule.NetworkModuleImpl.<init>(NetworkModuleImpl.java:100)
    at com.pcee.architecture.ModuleManagement.<init>(ModuleManagement.java:50)
    at com.pcee.server.ServerLauncher.main(ServerLauncher.java:32)

**Comment by jonesir** [comment]
this exceptions message is exactly the same on windows even if i only lunch the server instance once. which means the PCEE won't work on windows with current port.  
on fedora it's another story, launch the server and then the client, it works fine. since the port has been used by the first server, another instance will apparently give the above exception message.

**Comment by jonesir** [comment]
on fedora, one server instance and two client instances work also well.
